events { worker_connections 1024; }
http {
  upstream shell             { server host.docker.internal:3000; }
  upstream mfe_auth          { server host.docker.internal:3001; }
  upstream mfe_catalog       { server host.docker.internal:3002; }
  upstream mfe_cart          { server host.docker.internal:3003; }
  upstream mfe_checkout      { server host.docker.internal:3004; }
  upstream mfe_orders        { server host.docker.internal:3005; }
  upstream mfe_profile       { server host.docker.internal:3006; }
  upstream mfe_promotions    { server host.docker.internal:3007; }
  upstream mfe_notifications { server host.docker.internal:3008; }
  upstream mfe_admin         { server host.docker.internal:3009; }

  server {
    listen 80;
    location /auth/          { proxy_pass http://mfe_auth/; }
    location /products/      { proxy_pass http://mfe_catalog/; }
    location /cart/          { proxy_pass http://mfe_cart/; }
    location /checkout/      { proxy_pass http://mfe_checkout/; }
    location /orders/        { proxy_pass http://mfe_orders/; }
    location /profile/       { proxy_pass http://mfe_profile/; }
    location /promotions/    { proxy_pass http://mfe_promotions/; }
    location /notifications/ { proxy_pass http://mfe_notifications/; }
    location /admin/         { proxy_pass http://mfe_admin/; }
    location /               { proxy_pass http://shell/; }
  }
}
